INSERT INTO categories (user_id, name, group_name, icon, color, is_system) VALUES
(NULL, 'Aluguel', 'moradia', 'home', '#6366F1', TRUE),
(NULL, 'Condomínio', 'moradia', 'building', '#6366F1', TRUE),
(NULL, 'Energia', 'moradia', 'zap', '#6366F1', TRUE),
(NULL, 'Água', 'moradia', 'droplets', '#6366F1', TRUE),
(NULL, 'Gás', 'moradia', 'flame', '#6366F1', TRUE),
(NULL, 'Internet/Telefone', 'moradia', 'wifi', '#6366F1', TRUE),
(NULL, 'Combustível', 'transporte', 'fuel', '#F59E0B', TRUE),
(NULL, 'Uber/99', 'transporte', 'car', '#F59E0B', TRUE),
(NULL, 'Transporte Público', 'transporte', 'bus', '#F59E0B', TRUE),
(NULL, 'Estacionamento', 'transporte', 'parking-circle', '#F59E0B', TRUE),
(NULL, 'Supermercado', 'alimentação', 'shopping-cart', '#10B981', TRUE),
(NULL, 'Restaurante', 'alimentação', 'utensils', '#10B981', TRUE),
(NULL, 'Delivery', 'alimentação', 'bike', '#10B981', TRUE),
(NULL, 'Plano de Saúde', 'saúde', 'heart-pulse', '#EF4444', TRUE),
(NULL, 'Farmácia', 'saúde', 'pill', '#EF4444', TRUE),
(NULL, 'Consultas/Exames', 'saúde', 'stethoscope', '#EF4444', TRUE),
(NULL, 'Academia', 'saúde', 'dumbbell', '#EF4444', TRUE),
(NULL, 'Cursos', 'educação', 'graduation-cap', '#8B5CF6', TRUE),
(NULL, 'Livros', 'educação', 'book-open', '#8B5CF6', TRUE),
(NULL, 'Streaming', 'lazer', 'tv', '#EC4899', TRUE),
(NULL, 'Entretenimento', 'lazer', 'gamepad-2', '#EC4899', TRUE),
(NULL, 'Viagens', 'lazer', 'plane', '#EC4899', TRUE),
(NULL, 'Ferramentas/Software', 'trabalho', 'wrench', '#0EA5E9', TRUE),
(NULL, 'Marketing/Tráfego', 'trabalho', 'megaphone', '#0EA5E9', TRUE),
(NULL, 'Equipamentos', 'trabalho', 'monitor', '#0EA5E9', TRUE),
(NULL, 'Parcela de Dívida', 'financeiro', 'credit-card', '#DC2626', TRUE),
(NULL, 'Juros/IOF', 'financeiro', 'percent', '#DC2626', TRUE),
(NULL, 'Tarifa Bancária', 'financeiro', 'landmark', '#DC2626', TRUE),
(NULL, 'Investimento', 'financeiro', 'trending-up', '#059669', TRUE),
(NULL, 'Roupas', 'pessoal', 'shirt', '#D946EF', TRUE),
(NULL, 'Estética', 'pessoal', 'scissors', '#D946EF', TRUE),
(NULL, 'Pet', 'pessoal', 'dog', '#D946EF', TRUE),
(NULL, 'Salário/Pró-labore', 'renda', 'wallet', '#16A34A', TRUE),
(NULL, 'Freelance/Projetos', 'renda', 'briefcase', '#16A34A', TRUE),
(NULL, 'Rendimentos', 'renda', 'bar-chart-3', '#16A34A', TRUE),
(NULL, 'Outros (Receita)', 'renda', 'plus-circle', '#16A34A', TRUE),
(NULL, 'Outros (Despesa)', 'outros', 'help-circle', '#6B7280', TRUE);
